export const PERMISSIONS = [
  "BLOG_READ", "BLOG_WRITE", "BLOG_DELETE",
  "PRODUCT_READ", "PRODUCT_WRITE", "PRODUCT_DELETE",
  "ORDER_READ", "ORDER_UPDATE", "ORDER_REFUND",
  "BOOKING_READ", "BOOKING_UPDATE", "BOOKING_CANCEL",
  "PAYMENT_READ", "PAYMENT_REFUND",
  "USER_MANAGE", "SETTINGS_MANAGE",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_NAMES = [
  "SUPER_ADMIN", "CONTENT_MANAGER", "STORE_MANAGER", "CONSULTATION_MANAGER", "FINANCE_MANAGER",
] as const;
export type RoleName = (typeof ROLE_NAMES)[number];

export const ROLE_PERMISSIONS: Record<RoleName, readonly Permission[]> = {
  SUPER_ADMIN: PERMISSIONS,
  CONTENT_MANAGER: ["BLOG_READ", "BLOG_WRITE", "BLOG_DELETE"],
  STORE_MANAGER: [
    "PRODUCT_READ", "PRODUCT_WRITE", "PRODUCT_DELETE",
    "ORDER_READ", "ORDER_UPDATE", "PAYMENT_READ",
  ],
  CONSULTATION_MANAGER: ["BOOKING_READ", "BOOKING_UPDATE", "BOOKING_CANCEL", "PAYMENT_READ"],
  FINANCE_MANAGER: ["ORDER_READ", "BOOKING_READ", "PAYMENT_READ", "PAYMENT_REFUND", "ORDER_REFUND"],
};
