export const PERMISSIONS = [
  "BLOG_READ", "BLOG_WRITE", "BLOG_DELETE",
  "PRODUCT_READ", "PRODUCT_WRITE", "PRODUCT_DELETE",
  "ORDER_READ", "ORDER_UPDATE", "ORDER_REFUND",
  "CUSTOMER_READ", "CUSTOMER_MANAGE",
  "MEDIA_READ", "MEDIA_UPLOAD", "MEDIA_DELETE",
  "PAYMENT_READ", "PAYMENT_REFUND",
  "USER_MANAGE", "SETTINGS_MANAGE",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_NAMES = [
  "SUPER_ADMIN",
  "ADMIN",
  "EDITOR",
  "ORDER_MANAGER",
  "CONTENT_MANAGER",
  "STORE_MANAGER",
] as const;

export type RoleName = (typeof ROLE_NAMES)[number];

export const ROLE_PERMISSIONS: Record<RoleName, readonly Permission[]> = {
  SUPER_ADMIN: PERMISSIONS,
  ADMIN: [
    "BLOG_READ", "BLOG_WRITE", "BLOG_DELETE",
    "PRODUCT_READ", "PRODUCT_WRITE", "PRODUCT_DELETE",
    "ORDER_READ", "ORDER_UPDATE",
    "CUSTOMER_READ", "CUSTOMER_MANAGE",
    "MEDIA_READ", "MEDIA_UPLOAD", "MEDIA_DELETE",
    "PAYMENT_READ",
  ],
  EDITOR: [
    "BLOG_READ", "BLOG_WRITE", "BLOG_DELETE",
    "MEDIA_READ", "MEDIA_UPLOAD", "MEDIA_DELETE",
  ],
  ORDER_MANAGER: [
    "PRODUCT_READ",
    "ORDER_READ", "ORDER_UPDATE", "ORDER_REFUND",
    "CUSTOMER_READ", "CUSTOMER_MANAGE",
    "PAYMENT_READ",
  ],
  CONTENT_MANAGER: [
    "BLOG_READ", "BLOG_WRITE", "BLOG_DELETE",
    "MEDIA_READ", "MEDIA_UPLOAD", "MEDIA_DELETE",
  ],
  STORE_MANAGER: [
    "PRODUCT_READ", "PRODUCT_WRITE", "PRODUCT_DELETE",
    "ORDER_READ", "ORDER_UPDATE",
    "CUSTOMER_READ", "CUSTOMER_MANAGE",
    "PAYMENT_READ",
  ],
};
